mybatis:
    type-aliases-package: com.eastflag.domain
    type-handlers-package: com.eastflag.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

datasource:
  driverClassName: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://www.javabrain.kr:3306/jbdb?useUnicode=true&charaterEncoding=utf-8"
  userName: "********"
  password: "*******"
  initialSize: 10
  maxActive: 100
  maxIdle: 10
  minIdle: 10
  maxWait: 3000
  validationQuery: "SELECT 1"
  validationInterval: 36000
  testOnBorrow: "true"